openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8009/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:

  /send-email:
    post:
      summary: Endpoint used to dynamically send predefinded email templates
      security:
        - bearerAuth: []
      responses:
        '200':
          description: completed
        '403':
          description: Access not allowed
        '404':
          description: No projects available. Create and configure the project through UI and try again.
      parameters:
        - name: driver
          in: query
          description: Mail Driver Type
          required: true
          schema:
            type: string
        - name: template_id
          in: query
          description: Template ID to use while sending email
          required: true
          schema:
            type: string
        - name: to
          in: query
          description: Reciving email address
          required: true
          schema:
            type: string
        - name: subject
          in: query
          description: Reciving email address
          required: true
          schema:
            type: string
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200': 
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string



# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
- bearerAuth: []  